name: Deploy Content to azure-sentinel-e2e1-usx [dfd6aa42-05f8-40a5-a7ef-1d85e7116acb]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-dfd6aa42-05f8-40a5-a7ef-1d85e7116acb.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-dfd6aa42-05f8-40a5-a7ef-1d85e7116acb.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'azure-sentinel-e2e1'
      workspaceName: 'azure-sentinel-e2e1-usx'
      workspaceId: 'a44c77ec-50fe-4adf-a26a-6fc54a360829'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,Parser'
      branch: 'main'
      sourceControlId: 'dfd6aa42-05f8-40a5-a7ef-1d85e7116acb'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_dfd6aa4205f840a5a7ef1d85e7116acb }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-dfd6aa42-05f8-40a5-a7ef-1d85e7116acb.ps1